version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependencies"
      - "javascript"
      - "automated pr"
    schedule:
      interval: "monthly"
    target-branch: "alpha"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "github-actions"
    directory: "/.github"
    labels:
      - "dependencies"
      - "automated pr"
    schedule:
      interval: "monthly"
    target-branch: "alpha"
    assignees:
      - "lpm0073"
    reviewers:
      - "lpm0073"
  - package-ecosystem: "helm"
    directory: "/helm/charts/smarter"
    schedule:
      interval: "quarterly"
