apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-smarter-job-db-init-{{ now | unixEpoch }}"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: "{{ .Values.app.name }}-job-init"
  annotations:
    "helm.sh/hook": post-upgrade,post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Values.app.name }}-job-init"
        jobTimestamp: "{{ now | unixEpoch }}"
    spec:
      affinity:
        {{- toYaml .Values.global.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      automountServiceAccountToken: true
      containers:
        - resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "1"
          args:
            - |
              mysql -u "{{ .Values.env.SMARTER_MYSQL_ROOT_USERNAME }}" --password="{{ .Values.env.SMARTER_MYSQL_ROOT_PASSWORD }}" --host "{{ .Values.env.SMARTER_MYSQL_HOST }}" --port {{ .Values.env.SMARTER_MYSQL_PORT }} -e "CREATE DATABASE IF NOT EXISTS {{ .Values.env.SMARTER_MYSQL_DATABASE }};"
              mysql -u "{{ .Values.env.SMARTER_MYSQL_ROOT_USERNAME }}" --password="{{ .Values.env.SMARTER_MYSQL_ROOT_PASSWORD }}" --host "{{ .Values.env.SMARTER_MYSQL_HOST }}" --port {{ .Values.env.SMARTER_MYSQL_PORT }} -e "CREATE USER IF NOT EXISTS '{{ .Values.env.SMARTER_MYSQL_USER }}'@'%' IDENTIFIED BY '{{ .Values.env.SMARTER_MYSQL_PASSWORD }}';"
              mysql -u "{{ .Values.env.SMARTER_MYSQL_ROOT_USERNAME }}" --password="{{ .Values.env.SMARTER_MYSQL_ROOT_PASSWORD }}" --host "{{ .Values.env.SMARTER_MYSQL_HOST }}" --port {{ .Values.env.SMARTER_MYSQL_PORT }} -e "ALTER USER '{{ .Values.env.SMARTER_MYSQL_USER }}'@'%' IDENTIFIED BY '{{ .Values.env.SMARTER_MYSQL_PASSWORD }}';"
              mysql -u "{{ .Values.env.SMARTER_MYSQL_ROOT_USERNAME }}" --password="{{ .Values.env.SMARTER_MYSQL_ROOT_PASSWORD }}" --host "{{ .Values.env.SMARTER_MYSQL_HOST }}" --port {{ .Values.env.SMARTER_MYSQL_PORT }} -e "GRANT ALL PRIVILEGES ON {{ .Values.env.SMARTER_MYSQL_DATABASE }}.* TO '{{ .Values.env.SMARTER_MYSQL_USER }}'@'%'; FLUSH PRIVILEGES;"
              python manage.py makemigrations
              python manage.py migrate
              python manage.py initialize_platform --username "{{ .Values.env.SMARTER_ADMIN_USERNAME }}" --email "{{ .Values.env.SMARTER_ADMIN_USERNAME }}@{{ .Values.env.ROOT_DOMAIN }}" --password "{{ .Values.env.SMARTER_ADMIN_PASSWORD }}"
          command:
            - /bin/sh
            - -c
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $env := .Values.app.env }}
            - name: {{ $env.name }}
              value: {{ $env.value | quote }}
            {{- end }}
          image: '{{ .Values.env.SMARTER_DOCKER_IMAGE | default (printf "%s:%s" .Values.global.image.repository .Values.global.image.tag) }}'
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "IfNotPresent" }}
          name: "{{ .Values.app.name }}-job-init"
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Never
      schedulerName: default-scheduler
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
