apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-smarter-job-db-init-{{ now | unixEpoch }}"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: "{{ .Values.names.appName }}-job-init"
  annotations:
    "helm.sh/hook": post-upgrade,post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Values.names.appName }}-job-init"
        jobTimestamp: "{{ now | unixEpoch }}"
    spec:
      affinity:
        {{- toYaml .Values.global.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      automountServiceAccountToken: true
      containers:
        - resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "1"
          args:
            - |
              mysql -u "{{ .Values.env.MYSQL_ROOT_USERNAME }}" --password="{{ .Values.env.MYSQL_ROOT_PASSWORD }}" --host "{{ .Values.env.MYSQL_HOST }}" --port {{ .Values.env.MYSQL_PORT }} -e "CREATE DATABASE IF NOT EXISTS {{ .Values.env.MYSQL_DATABASE }};"
              mysql -u "{{ .Values.env.MYSQL_ROOT_USERNAME }}" --password="{{ .Values.env.MYSQL_ROOT_PASSWORD }}" --host "{{ .Values.env.MYSQL_HOST }}" --port {{ .Values.env.MYSQL_PORT }} -e "CREATE USER IF NOT EXISTS '{{ .Values.env.MYSQL_USER }}'@'%' IDENTIFIED BY '{{ .Values.env.MYSQL_PASSWORD }}';"
              mysql -u "{{ .Values.env.MYSQL_ROOT_USERNAME }}" --password="{{ .Values.env.MYSQL_ROOT_PASSWORD }}" --host "{{ .Values.env.MYSQL_HOST }}" --port {{ .Values.env.MYSQL_PORT }} -e "ALTER USER '{{ .Values.env.MYSQL_USER }}'@'%' IDENTIFIED BY '{{ .Values.env.MYSQL_PASSWORD }}';"
              mysql -u "{{ .Values.env.MYSQL_ROOT_USERNAME }}" --password="{{ .Values.env.MYSQL_ROOT_PASSWORD }}" --host "{{ .Values.env.MYSQL_HOST }}" --port {{ .Values.env.MYSQL_PORT }} -e "GRANT ALL PRIVILEGES ON {{ .Values.env.MYSQL_DATABASE }}.* TO '{{ .Values.env.MYSQL_USER }}'@'%'; FLUSH PRIVILEGES;"
              python manage.py makemigrations
              python manage.py migrate
              python manage.py initialize_platform --username "{{ .Values.env.SMARTER_ADMIN_USERNAME }}" --email "{{ .Values.env.SMARTER_ADMIN_USERNAME }}@{{ .Values.env.ROOT_DOMAIN }}" --password "{{ .Values.env.SMARTER_ADMIN_PASSWORD }}"
          command:
            - /bin/sh
            - -c
          env:
            - name: ROOT_DOMAIN
              value: "{{ .Values.env.ROOT_DOMAIN }}"

            - name: AWS_REGION
              value: "{{ .Values.env.AWS_REGION }}"

            - name: AWS_ACCESS_KEY_ID
              value: "{{ .Values.env.AWS_ACCESS_KEY_ID }}"

            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.env.AWS_SECRET_ACCESS_KEY}}"

            - name: AUTHENTICATION_BACKENDS
              value: "{{ .Values.env.AUTHENTICATION_BACKENDS }}"

            - name: DEBUG_MODE
              value: "{{ .Values.env.DEBUG_MODE }}"

            - name: DOCKERHUB_PAT
              value: "{{ .Values.env.DOCKERHUB_PAT }}"

            - name: DOCKERHUB_USERNAME
              value: "{{ .Values.env.DOCKERHUB_USERNAME }}"

            - name: DUMP_DEFAULTS
              value: "{{ .Values.env.DUMP_DEFAULTS }}"

            - name: SECRET_KEY
              value: "{{ .Values.env.SECRET_KEY }}"

            - name: SMARTER_ADMIN_EMAIL
              value: "{{ .Values.env.SMARTER_ADMIN_EMAIL }}"

            - name: SMARTER_ADMIN_PASSWORD
              value: "{{ .Values.env.SMARTER_ADMIN_PASSWORD }}"

            - name: SMARTER_ADMIN_USERNAME
              value: "{{ .Values.env.SMARTER_ADMIN_USERNAME }}"

            - name: SMARTER_AWS_EKS_CLUSTER_NAME
              value: "{{ .Values.env.SMARTER_AWS_EKS_CLUSTER_NAME }}"

            - name: SMARTER_AWS_RDS_DB_INSTANCE_IDENTIFIER
              value: "{{ .Values.env.SMARTER_AWS_RDS_DB_INSTANCE_IDENTIFIER }}"

            - name: SMARTER_COHERE_API_KEY
              value: "{{ .Values.env.SMARTER_COHERE_API_KEY }}"

            - name: SMARTER_CONFIGURE_UBC_ACCOUNT
              value: "{{ .Values.env.SMARTER_CONFIGURE_UBC_ACCOUNT }}"

            - name: SMARTER_CONFIGURE_BETA_ACCOUNT
              value: "{{ .Values.env.SMARTER_CONFIGURE_BETA_ACCOUNT }}"

            - name: SMARTER_EMAIL_ADMINS
              value: "{{ .Values.env.SMARTER_EMAIL_ADMINS }}"

            - name: SMARTER_FERNET_ENCRYPTION_KEY
              value: "{{ .Values.env.SMARTER_FERNET_ENCRYPTION_KEY }}"

            - name: SMARTER_FIREWORKS_API_KEY
              value: "{{ .Values.env.SMARTER_FIREWORKS_API_KEY }}"

            - name: SMARTER_GEMINI_API_KEY
              value: "{{ .Values.env.SMARTER_GEMINI_API_KEY }}"

            - name: SMARTER_GOOGLE_MAPS_API_KEY
              value: "{{ .Values.env.SMARTER_GOOGLE_MAPS_API_KEY }}"

            - name: SMARTER_GOOGLE_SERVICE_ACCOUNT_B64
              value: "{{ .Values.env.SMARTER_GOOGLE_SERVICE_ACCOUNT_B64 }}"

            - name: SMARTER_INTERNAL_IP_PREFIXES
              value: "{{ .Values.env.SMARTER_INTERNAL_IP_PREFIXES }}"

            - name: SMARTER_LLAMA_API_KEY
              value: "{{ .Values.env.SMARTER_LLAMA_API_KEY }}"

            - name: SMARTER_LLAMA_API_KEY
              value: "{{ .Values.env.SMARTER_LLAMA_API_KEY }}"

            - name: SMARTER_MISTRAL_API_KEY
              value: "{{ .Values.env.SMARTER_MISTRAL_API_KEY }}"

            - name: SMARTER_MYSQL_DATABASE
              value: "{{ .Values.env.SMARTER_MYSQL_DATABASE }}"

            - name: SMARTER_MYSQL_HOST
              value: "{{ .Values.env.SMARTER_MYSQL_HOST }}"

            - name: SMARTER_MYSQL_PASSWORD
              value: "{{ .Values.env.SMARTER_MYSQL_PASSWORD }}"

            - name: SMARTER_MYSQL_PORT
              value: "{{ .Values.env.SMARTER_MYSQL_PORT }}"

            - name: SMARTER_MYSQL_ROOT_PASSWORD
              value: "{{ .Values.env.SMARTER_MYSQL_ROOT_PASSWORD }}"

            - name: SMARTER_MYSQL_ROOT_USERNAME
              value: "{{ .Values.env.SMARTER_MYSQL_ROOT_USERNAME }}"

            - name: SMARTER_MYSQL_TEST_DATABASE_PASSWORD
              value: "{{ .Values.env.SMARTER_MYSQL_TEST_DATABASE_PASSWORD }}"

            - name: SMARTER_MYSQL_TEST_DATABASE_SECRET_NAME
              value: "{{ .Values.env.SMARTER_MYSQL_TEST_DATABASE_SECRET_NAME }}"

            - name: SMARTER_MYSQL_USER
              value: "{{ .Values.env.SMARTER_MYSQL_USER }}"

            - name: SMARTER_OPENAI_API_KEY
              value: "{{ .Values.env.SMARTER_OPENAI_API_KEY }}"

            - name: SMARTER_PINECONE_API_KEY
              value: "{{ .Values.env.SMARTER_PINECONE_API_KEY }}"

            - name: SMARTER_PINECONE_ENVIRONMENT
              value: "{{ .Values.env.SMARTER_PINECONE_ENVIRONMENT }}"

            - name: SMARTER_PLUGIN_MAX_DATA_RESULTS
              value: "{{ .Values.env.SMARTER_PLUGIN_MAX_DATA_RESULTS }}"

            - name: SMARTER_REACTJS_APP_LOADER_PATH
              value: "{{ .Values.env.SMARTER_REACTJS_APP_LOADER_PATH }}"

            - name: SMARTER_ROOT_DOMAIN
              value: "{{ .Values.env.SMARTER_ROOT_DOMAIN }}"

            - name: SMARTER_SETTINGS_OUTPUT_FORMAT
              value: "{{ .Values.env.SMARTER_SETTINGS_OUTPUT_FORMAT }}"

            - name: SMARTER_SMTP_FROM_EMAIL
              value: "{{ .Values.env.SMARTER_SMTP_FROM_EMAIL }}"

            - name: SMARTER_SMTP_PASSWORD
              value: "{{ .Values.env.SMARTER_SMTP_PASSWORD }}"

            - name: SMARTER_SMTP_SENDER
              value: "{{ .Values.env.SMARTER_SMTP_SENDER }}"

            - name: SMARTER_SMTP_USERNAME
              value: "{{ .Values.env.SMARTER_SMTP_USERNAME }}"

            - name: SMARTER_TOGETHERAI_API_KEY
              value: "{{ .Values.env.SMARTER_TOGETHERAI_API_KEY }}"

            - name: SMTP_HOST
              value: "{{ .Values.env.SMTP_HOST }}"

            - name: SMTP_PORT
              value: "{{ .Values.env.SMTP_PORT }}"

            - name: SMTP_USE_SSL
              value: "{{ .Values.env.SMTP_USE_SSL }}"

            - name: SMTP_USE_TLS
              value: "{{ .Values.env.SMTP_USE_TLS }}"

          image: '{{ .Values.env.SMARTER_DOCKER_IMAGE | default (printf "%s:%s" .Values.global.image.repository .Values.global.image.tag) }}'
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "IfNotPresent" }}
          name: "{{ .Values.names.appName }}-job-init"
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Never
      schedulerName: default-scheduler
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
