{{- if and .Values.mysql.enabled .Values.mysql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name | default "smarter" }}-{{ .Values.names.mysqlName | default "mysql" }}
  namespace: {{ .Values.namespace }}
  labels:
    App: {{ .Values.app.name | default "smarter" }}-{{ .Values.names.mysqlName | default "mysql" }}
spec:
  accessModes:
    {{- toYaml .Values.mysql.persistence.accessModes | nindent 4 }}
  {{- if .Values.mysql.persistence.storageClassName }}
  storageClassName: {{ .Values.mysql.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
{{- end }}
