apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.names.appName }}"
  namespace: "{{ .Values.env.NAMESPACE }}"

spec:
  selector:
    app.kubernetes.io/name: "{{ .Values.names.appName }}"
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  sessionAffinity: None
  type: ClusterIP
