# ------------------------------------------------------------------------------
# Artifact Hub repository metadata file
#
# Some settings like the verified publisher flag or the ignored packages won't
# be applied until the next time the repository is processed. Please keep in
# mind that the repository won't be processed if it has not changed since the
# last time it was processed. Depending on the repository kind, this is checked
# in a different way. For Helm http based repositories, we consider it has
# changed if the `index.yaml` file changes. For git based repositories, it does
# when the hash of the last commit in the branch you set up changes. This does
# NOT apply to ownership claim operations, which are processed immediately.
# ------------------------------------------------------------------------------

# The ID of the Artifact Hub repository where the packages will be published to (optional, but it enables verified publisher)
repositoryID: 02c1a0d4-b6e7-4c02-9143-6ee9744012b7
owners:
  - name: Lawrence McDaniel
    email: lpm0073@gmail.com

displayName: Smarter Api and web console Helm Charts
url: https://github.com/smarter-sh/smarter/tree/main/helm/charts/smarter

description: |
  Helm charts for deploying the Smarter Api and web console

links:
  - name: Website
    url: https://smarter.sh
  - name: GitHub
    url: https://github.com/smarter-sh/smarter
  - name: Documentation
    url: https://platform.smarter.sh/docs/
  - name: Support
    url: https://github.com/smarter-sh/smarter/issues

scannerDisabled: false
