---
#------------------------------------------------------------------------------
# - Deploy to AWS Elastic Kubernetes Service (EKS)
#
# IMPORTANT: Before running this workflow, ensure that you have first built your
# AWS infrastructure using the [Smarter Infrastructure repository](https://github.com/smarter-sh/smarter-infrastructure).
# Additionally, make sure the following secrets are configured in your
# [GitHub repository settings](https://github.com/smarter-sh/smarter/settings/secrets/actions):
#
# AWS_ACCESS_KEY_ID
# AWS_REGION
# AWS_SECRET_ACCESS_KEY
# FERNET_ENCRYPTION_KEY
# GEMINI_API_KEY
# GOOGLE_AI_STUDIO_KEY
# GOOGLE_MAPS_API_KEY
# GOOGLE_SERVICE_ACCOUNT_B64
# LLAMA_API_KEY
# MAILCHIMP_API_KEY
# MAILCHIMP_LIST_ID
# OPENAI_API_KEY
# PAT
# PINECONE_API_KEY
# PINECONE_ENVIRONMENT
# SMARTER_MYSQL_TEST_DATABASE_PASSWORD
# SMTP_PASSWORD
# SMTP_USERNAME
# SOCIAL_AUTH_GITHUB_KEY
# SOCIAL_AUTH_GITHUB_SECRET
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
# SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY
# SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET
#------------------------------------------------------------------------------
name: Deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ROOT_DOMAIN: "smarter.sh"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v5

      - name: Set environment variable
        id: setenv
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/alpha" ]]; then
            echo "ENVIRONMENT=alpha" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/beta" ]]; then
            echo "ENVIRONMENT=beta" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/next" ]]; then
            echo "ENVIRONMENT=next" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          else
            echo "This workflow can only run on alpha, beta, next, or main branches"
            exit 1
          fi

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          environment: ${{ env.ENVIRONMENT }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-pat: ${{ secrets.DOCKERHUB_PAT }}
          fernet-encryption-key: ${{ secrets.FERNET_ENCRYPTION_KEY }}
          google-maps-api-key: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          llama-api-key: ${{ secrets.LLAMA_API_KEY }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          pinecone-api-key: ${{ secrets.PINECONE_API_KEY }}
          pinecone-environment: ${{ secrets.PINECONE_ENVIRONMENT }}
          smarter-mysql-test_database_password: ${{ secrets.SMARTER_MYSQL_TEST_DATABASE_PASSWORD}}
          social-auth-google-oauth2-key: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }}
          social-auth-google-oauth2-secret: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }}
          social-auth-github-key: ${{ secrets.SOCIAL_AUTH_GITHUB_KEY }}
          social-auth-github-secret: ${{ secrets.SOCIAL_AUTH_GITHUB_SECRET }}
          social-auth-linkedin-oauth2-key: ${{ secrets.SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY }}
          social-auth-linkedin-oauth2-secret: ${{ secrets.SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET }}
          mailchimp-api-key: ${{ secrets.MAILCHIMP_API_KEY }}
          mailchimp-list-id: ${{ secrets.MAILCHIMP_LIST_ID }}

      - name: Send Email
        uses: ./.github/actions/send-mail
        with:
          environment: ${{ env.ENVIRONMENT }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          subject: "GHA - Deployed ${{ env.ENVIRONMENT }}.platform.smarter.sh"
          body: "${{ env.ENVIRONMENT }}.platform.smarter.sh was deployed successfully."
